### ISSUE TITLE
JSON serialization support

### ISSUE THREAD

**Issue by cheesycod** [mhmtszr/concurrent-swiss-map#11]
@mhmtszr would it be possible to add/implement ``MarshalJSON`` and ``UnmarshalJSON`` (basically json marshal/unmarshal support). Should be as simple as Ranging over all elements to make a map or smth.

**Comment by mhmtszr** [comment]
@cheesycod thanks for the contribution i added marshal and unmarshal support with version 1.0.8 https://github.com/mhmtszr/concurrent-swiss-map/releases/tag/v1.0.8.
