### ISSUE TITLE
proposal: Define `New()` function instead of `Create()`

### ISSUE THREAD

**Issue by gozeloglu** [mhmtszr/concurrent-swiss-map#18]
Hi,

I want to suggest a change in the API. Currently, `*CsMap[K, V]` is defined with `Create()` function. However, as you know, the general convention is the `New()` functions. It is kind of a naming convention in Go. I suggest to rename the `Create()` function to `New()` function. 

### Current

```go
myMap := csmap.Create[string, int]()
```

### Proposed function

```go
myMap := csmap.New[string, int]()
```

### Backward-compatibility

One of the important questions can be backward compatibility for the API. Currently, the latest version is `v1.0.8`. If you don't want to break the backward compatibility, you can keep both functions, `Create()` and `New()`. With `v2.0.0`, you can deprecate the `Create()` function and go with `New()`. Maybe you can release the `v2.0.0` version after the change.

### Option function type

Currently, there is no option function type. Also, it can be defined without breaking anything else. It can increase the readability. 

```go
type OptFunc[K comparable, V any] func(o *CsMap[K, V])

func New[K comparable, V any](options ...OptFunc[K, V]) *CsMap[K, V] {
	csMap := &CsMap[K, V]{}
	for _, opt := range options {
		opt(csMap)
	}
	return csMap
}
```

**Comment by mhmtszr** [comment]
Hello,

Good idea could you open MR for this?
