### ISSUE TITLE
Efficent way to delete element

### ISSUE THREAD

**Issue by artificialintelligence4all** [mhmtszr/concurrent-swiss-map#7]
Hi,

i was trying to create a function called deleteOlderThanOneMinute() that will delete the element that have a value older than a minute but i don't figure it out a correct and fast way to handle this task, can you tell me how can i do it? Following the code that i actually use to test your library. 
```go
import (
	"fmt"
	"time"
	csmap "github.com/mhmtszr/concurrent-swiss-map"
)

var m = csmap.Createstring, int64,
	csmap.WithSizestring, int64,
)

func main() {
	hash := "hash1"
	timestamp := time.Now().Unix()
	m.Store(hash, timestamp)
	hash2 := "hash2"
	timestampOld2Minute := time.Now().Add(-2 * time.Minute).Unix()
	m.Store(hash2, timestampOld2Minute)
	hash3 := "hash3"
	timestampOld3Minute := time.Now().Add(-3 * time.Minute).Unix()
	m.Store(hash3, timestampOld3Minute)
	count := m.Count()
	println("count:", count)
	m.Range(func(key string, value int64) (stop bool) {
		fmt.Printf("Key: %s, Value: %d\n", key, value)
		return false // continue
	})
	deleteOlderThanOneMinute()
}

**Comment by mhmtszr** [comment]
Hi,

Thanks for the contribution. `time.AfterFunc` can be used here but this feature is out of the context of concurrent-swiss-map. You may fork and create your own cache library or wrap the library.
