### ISSUE TITLE
Deleting from within a Range will result in deadlock

### ISSUE THREAD

**Issue by SoftExpert** [mhmtszr/concurrent-swiss-map#8]
Hello,

First of all, thank you for sharing this nice library !

I think I have found a bug - deleting from within a **Range** will result in deadlock.
Here is an example :

```go
func TestSwissDeleteFromRange(t *testing.T) {
	smp := csmap.Create[string, int](
		csmap.WithSize[string, int](1024),
	)

	smp.Store("aaa", 10)
	smp.Store("aab", 11)
	smp.Store("aac", 15)
	smp.Store("aad", 124)
	smp.Store("aaf", 987)

	smp.Range(func(key string, value int) (stop bool) {
		if value > 20 {
			smp.Delete(key)
		}
		return false
	})
	t.Log("done")
}

```

The reason for trying to delete items from within the Range loop is item eviction based on arbitrary criteria (could be time based or just a range of values).

Is this the expected behavior or the logic is incomplete ?

Thanks for the feedback !

Best regards,
SoftExpert

**Comment by mhmtszr** [comment]
Hello,

Thanks for the contribution. While iterating over the map we are rlocking the shard if we remove that we can get rid of this problem but I'm investigating if It's going to create a new race condition or not. What do you think?
